# Generated by Django 4.0.1 on 2022-01-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardApps', '0002_post00'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(max_length=50)),
                ('writer', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contents', models.TextField()),
                ('postdate', models.DateField()),
                ('visitcount', models.CharField(max_length=50)),
                ('file', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
